### ISSUE TITLE
NFT Collection Support

### ISSUE THREAD

**Issue by 1dolinski** [wagmilabs/deso-graphql#1]
Hey man, awesome repo! Love it.

Was wondering if there is support or plans to support pulling NFT Collections? https://docs.deso.org/backend/blockchain-data/basics/data-types

<img width="868" alt="image" src="https://user-images.githubusercontent.com/1243216/152695670-7b75883d-fc4b-46ec-859d-2eaed14accf9.png">

**Comment by chafreaky** [comment]
Hey! Not sure how I missed this but of course - will add this in in the coming days.

**Comment by 1dolinski** [comment]
@chafreaky awesome, thanks dude!

**Comment by chafreaky** [comment]
@1dolinski All done! It's been pushed, here's an example of a query using it:

```gql
{
  getNFTCollectionSummary(input: {
    NFTHashHex:"274bc76cf7711f9e9ec025dced7d5f02d2eabc6ae8291f2175e77cff648d157e"
  } ) {
    NFTHashHex
    NumCopiesBuyNow
    HighestBidAmountNanos
    AvailableSerialNumbers
  }
}

```
